DEBUG 2024-07-08 19:32:56.665 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-07-08 19:32:56.665 UTC: 	 Running on: Linux lxplus809.cern.ch 4.18.0-553.8.1.el8_10.x86_64 #1 SMP Fri Jun 14 03:19:37 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-07-08 19:32:56.665 UTC: 	 Executing command: 'status'
DEBUG 2024-07-08 19:32:56.665 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sobarman/.crab3
ERROR 2024-07-08 19:32:56.695 UTC: 	 Error: crab_projects/crab_Pt-15to7000_TuneCH3_Flat_herwig7 is not a valid CRAB project directory.
ERROR 2024-07-08 19:32:56.695 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_Pt-15to7000_TuneCH3_Flat_herwig7 is not a valid CRAB project directory.
INFO 2024-07-08 19:32:56.698 UTC: 	 Log file is /afs/cern.ch/work/s/sobarman/private/JCO2018/CMSSW_10_6_30/src/Test/QCDEventShape/test/crab.log
DEBUG 2024-07-09 19:20:33.141 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-07-09 19:20:33.141 UTC: 	 Running on: Linux lxplus801.cern.ch 4.18.0-553.5.1.el8_10.x86_64 #1 SMP Tue May 21 03:13:04 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-07-09 19:20:33.141 UTC: 	 Executing command: 'submit'
DEBUG 2024-07-09 19:20:33.141 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sobarman/.crab3
DEBUG 2024-07-09 19:20:33.142 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
DEBUG 2024-07-10 10:12:51.173 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-07-10 10:12:51.174 UTC: 	 Running on: Linux lxplus802.cern.ch 4.18.0-553.5.1.el8_10.x86_64 #1 SMP Tue May 21 03:13:04 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-07-10 10:12:51.174 UTC: 	 Executing command: 'resubmit'
DEBUG 2024-07-10 10:12:51.174 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sobarman/.crab3
DEBUG 2024-07-13 14:31:52.427 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-07-13 14:31:52.427 UTC: 	 Running on: Linux lxplus807.cern.ch 4.18.0-553.8.1.el8_10.x86_64 #1 SMP Fri Jun 14 03:19:37 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-07-13 14:31:52.427 UTC: 	 Executing command: 'resubmit'
DEBUG 2024-07-13 14:31:52.428 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sobarman/.crab3
DEBUG 2024-07-30 13:11:44.345 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-07-30 13:11:44.346 UTC: 	 Running on: Linux lxplus808.cern.ch 4.18.0-553.8.1.el8_10.x86_64 #1 SMP Fri Jun 14 03:19:37 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-07-30 13:11:44.346 UTC: 	 Executing command: 'resubmit'
DEBUG 2024-07-30 13:11:44.346 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sobarman/.crab3
DEBUG 2024-12-10 13:22:38.969 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-10 13:22:38.970 UTC: 	 Running on: Linux lxplus824.cern.ch 4.18.0-553.22.1.el8_10.x86_64 #1 SMP Wed Sep 11 18:02:00 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-10 13:22:38.970 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2024-12-10 13:22:38.970 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-10 13:22:38.970 UTC: 	 Executing command: 'status'
DEBUG 2024-12-10 13:22:38.970 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sobarman/.crab3
ERROR 2024-12-10 13:22:38.970 UTC: 	 Error: crab_projects/crab_Pt-15to7000_TuneCH3_Flat_herwig7 is not a valid CRAB project directory.
ERROR 2024-12-10 13:22:38.970 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_Pt-15to7000_TuneCH3_Flat_herwig7 is not a valid CRAB project directory.
INFO 2024-12-10 13:22:38.980 UTC: 	 Log file is /afs/cern.ch/work/s/sobarman/private/MiniAODJCO2018/CMSSW_10_6_30/src/Analysis/MiniAODAnalyzer/test/crab.log
DEBUG 2024-12-11 06:17:36.290 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 06:17:36.291 UTC: 	 Running on: Linux lxplus828.cern.ch 4.18.0-553.22.1.el8_10.x86_64 #1 SMP Wed Sep 11 18:02:00 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 06:17:36.291 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2024-12-11 06:17:36.291 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 06:17:36.291 UTC: 	 Executing command: 'status'
DEBUG 2024-12-11 06:17:36.291 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sobarman/.crab3
ERROR 2024-12-11 06:17:36.291 UTC: 	 Error: crab_projects/crab_Pt-15to7000_TuneCH3_Flat_herwig7 is not a valid CRAB project directory.
ERROR 2024-12-11 06:17:36.291 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_Pt-15to7000_TuneCH3_Flat_herwig7 is not a valid CRAB project directory.
INFO 2024-12-11 06:17:36.319 UTC: 	 Log file is /afs/cern.ch/work/s/sobarman/private/MiniAODJCO2018/CMSSW_10_6_30/src/Analysis/MiniAODAnalyzer/test/crab.log
DEBUG 2024-12-18 05:47:26.161 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-18 05:47:26.161 UTC: 	 Running on: Linux lxplus824.cern.ch 4.18.0-553.22.1.el8_10.x86_64 #1 SMP Wed Sep 11 18:02:00 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-18 05:47:26.161 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2024-12-18 05:47:26.161 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-18 05:47:26.161 UTC: 	 Executing command: 'status'
DEBUG 2024-12-18 05:47:26.162 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sobarman/.crab3
ERROR 2024-12-18 05:47:26.162 UTC: 	 Error: crab_projects/crab_Pt-15to7000_TuneCH3_Flat_herwig7 is not a valid CRAB project directory.
ERROR 2024-12-18 05:47:26.162 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_Pt-15to7000_TuneCH3_Flat_herwig7 is not a valid CRAB project directory.
INFO 2024-12-18 05:47:26.177 UTC: 	 Log file is /afs/cern.ch/work/s/sobarman/private/MiniAODJCO2018/CMSSW_10_6_30/src/Analysis/MiniAODAnalyzer/test/crab.log
DEBUG 2025-02-27 05:27:17.508 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-02-27 05:27:17.508 UTC: 	 Running on: Linux lxplus818.cern.ch 4.18.0-553.40.1.el8_10.x86_64 #1 SMP Thu Feb 6 21:20:51 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-02-27 05:27:17.508 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2025-02-27 05:27:17.508 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-02-27 05:27:17.508 UTC: 	 Executing command: 'submit'
DEBUG 2025-02-27 05:27:17.509 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sobarman/.crab3
DEBUG 2025-02-27 05:27:17.560 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
DEBUG 2025-02-27 05:32:13.304 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-02-27 05:32:13.304 UTC: 	 Running on: Linux lxplus818.cern.ch 4.18.0-553.40.1.el8_10.x86_64 #1 SMP Thu Feb 6 21:20:51 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-02-27 05:32:13.304 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2025-02-27 05:32:13.304 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-02-27 05:32:13.304 UTC: 	 Executing command: 'status'
DEBUG 2025-02-27 05:32:13.305 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sobarman/.crab3
ERROR 2025-02-27 05:32:13.305 UTC: 	 Error: crab_projects/crab_Pt-15to7000_TuneCH3_Flat_herwig7 is not a valid CRAB project directory.
ERROR 2025-02-27 05:32:13.305 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_Pt-15to7000_TuneCH3_Flat_herwig7 is not a valid CRAB project directory.
INFO 2025-02-27 05:32:13.307 UTC: 	 Log file is /afs/cern.ch/work/s/sobarman/private/MiniAODJCO2018_04Feb2025/CMSSW_10_6_30/src/Analysis/MiniAODAnalyzer/test/crab.log
DEBUG 2025-03-06 07:30:10.570 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-03-06 07:30:10.570 UTC: 	 Running on: Linux lxplus811.cern.ch 4.18.0-553.33.1.el8_10.x86_64 #1 SMP Fri Dec 6 15:07:20 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-03-06 07:30:10.570 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2025-03-06 07:30:10.570 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-03-06 07:30:10.570 UTC: 	 Executing command: 'status'
DEBUG 2025-03-06 07:30:10.570 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sobarman/.crab3
ERROR 2025-03-06 07:30:10.571 UTC: 	 Error: crab_projects/crab_projects/crab_Pt-15to7000_TuneCP5_Flat_pythia8 is not a valid CRAB project directory.
ERROR 2025-03-06 07:30:10.571 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_projects/crab_Pt-15to7000_TuneCP5_Flat_pythia8 is not a valid CRAB project directory.
INFO 2025-03-06 07:30:10.592 UTC: 	 Log file is /afs/cern.ch/work/s/sobarman/private/MiniAODJCO2018_04Feb2025/CMSSW_10_6_30/src/Analysis/MiniAODAnalyzer/test/crab.log
